---
- name: Ensure install bash
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - bash
    - bash-completion

- name: Install bash config
  copy:
    src: "bashrc"
    dest: "{{ home_path }}/.bashrc"
  become: no
