---
- name: check if home directory exists
  stat:
    path: "{{ home_path }}"
  become: false
  register: home
  tags: dotfiles

- name: create home directory
  file:
    path: "{{ home_path }}/bin"
    state: directory
    mode: 0755
  become: false
  when: not home.stat.exists
  tags: dotfiles

- name: copy bashrc dotfile
  copy:
    src: "{{ item }}"
    dest: "{{ home_path }}/.bashrc"
    mode: 0644
  become: false
  with_fileglob:
    - "bash/.bashrc"
  tags:
    - dotfiles
    - bashrc

- name: copy tmux dotfile
  copy:
    src: "{{ item }}"
    dest: "{{ home_path }}/.tmux.conf"
    mode: 0644
  become: false
  with_fileglob:
    - "tmux/.tmux.conf"
  tags:
    - dotfiles
    - tmux

- name: copy git dotfile
  copy:
    src: "{{ item }}"
    dest: "{{ home_path }}/.gitconfig"
    mode: 0644
  become: false
  with_fileglob:
    - "git/.gitconfig"
  tags:
    - dotfiles
    - git
