---
- name: check if home directory exists
  stat:
    path: "{{ home_path }}"
  become: false
  register: home
  tags: dotfiles

- name: create home directory
  file:
    path: "{{ home_path }}"
    state: directory
    mode: 0755
  become: false
  when: not home.stat.exists
  tags: dotfiles

- name: check if ~/bin directory exists
  stat:
    path: "{{ home_path }}/bin"
  become: false
  register: bin
  tags: dotfiles

- name: create ~/bin directory
  file:
    path: "{{ home_path }}/bin"
    state: directory
    mode: 0755
  become: false
  when: not bin.stat.exists
  tags: dotfiles

- name: copy bashrc dotfile
  copy:
    src: "{{ item }}"
    dest: "{{ home_path }}/.bashrc"
    mode: 0644
  become: false
  with_fileglob:
    - "bash/.bashrc"
  tags:
    - dotfiles
    - bashrc

- name: check if nash directory exists
  stat:
    path: "{{ home_path }}/nash"
  become: false
  register: nash
  tags:
    - dotfiles
    - nash

- name: create nash directory
  file:
    path: "{{ home_path }}/nash"
    state: directory
    mode: 0755
  become: false
  when: not nash.stat.exists
  tags:
    - dotfiles
    - nash

- name: copy nash dotfiles
  copy:
    src: "nash/"
    dest: "{{ home_path }}/nash"
    mode: preserve
  become: false
  tags:
    - dotfiles
    - nash

- name: copy tmux dotfile
  copy:
    src: "{{ item }}"
    dest: "{{ home_path }}/.tmux.conf"
    mode: 0644
  become: false
  with_fileglob:
    - "tmux/.tmux.conf"
  tags:
    - dotfiles
    - tmux

- name: copy git dotfile
  copy:
    src: "{{ item }}"
    dest: "{{ home_path }}/.gitconfig"
    mode: 0644
  become: false
  with_fileglob:
    - "git/.gitconfig"
  tags:
    - dotfiles
    - git

- name: check if local fonts directory exists
  stat:
    path: "{{ home_path }}/.local/share/fonts/truetype"
  become: false
  register: fonts
  tags:
    - dotfiles
    - fonts

- name: create local fonts directory
  file:
    path: "{{ home_path }}/.local/share/fonts/truetype"
    state: directory
    mode: 0755
  become: false
  when: not fonts.stat.exists
  tags:
    - dotfiles
    - fonts

- name: copy local fonts
  copy:
    src: "fonts/"
    dest: "{{ home_path }}/.local/share/fonts/truetype"
    mode: preserve
  become: false
  tags:
    - dotfiles
    - fonts

