---
- name: disable ipv6 module
  copy:
    src: "etc/modprobe.d/ipv6-blacklist.conf"
    dest: "/etc/modprobe.d/ipv6-blacklist.conf"
    owner: root
    group: root
    mode: '0644'
  tags: ipv6

- name: disable ipv6 sysctl's
  copy:
    src: "etc/sysctl.d/95-ipv6.conf"
    dest: "/etc/sysctl.d/95-ipv6.conf"
    owner: root
    group: root
    mode: '0644'
  tags: ipv6
