---
- name: add/enable rpmfusion repositories [free, nonfree]
  dnf:
    disable_gpg_check: true
    name: [ "{{ repo_rpmfusion | join(',') }}" ]
    state: present
  tags:
    - packages

- name: add/enable iridium repository
  command: dnf config-manager --add-repo "{{ repo_iridium }}"
  tags:
    - packages

- name: add osquery repository gpg key
  rpm_key:
    state: present
    key: "{{ rpm_gpp_key_osquery }}"
  tags:
    - packages

- name: add/enable osquery repository
  command: dnf config-manager --add-repo "{{ repo_osquery }}"
  tags:
    - packages

- name: add/enable dropbox repository
  copy:
    src: "etc/yum.repos.d/dropbox.repo"
    dest: "/etc/yum.repos.d/dropbox.repo"
    owner: root
    group: root
    mode: 0644
  tags:
    - packages

- name: install packages
  dnf:
    name: "{{ packages }}"
    state: present
  tags:
    - packages

- name: install third party packages [keybase, zoom]
  dnf:
    disable_gpg_check: true
    name: [ "{{ package_third_party | join(',') }}" ]
    state: present
  tags:
    - keybase
    - packages
    - zoom

- name: check if nashroot directory exists
  stat:
    path: "{{ home_path }}/nashroot"
  become: false
  register: nashroot
  tags:
    - dotfiles
    - nash

- name: install nash
  shell: |
    GOPATH="{{ golang_path }}" go get -d github.com/madlambda/nash
    cd "{{ golang_path}}/src/github.com/madlambda/nash/" && NASHROOT="{{ home_path }}/nashroot" make install
  args:
    executable: /usr/bin/bash
  become: false
  when: not nashroot.stat.exists
  tags:
    - nash
    - packages

- name: autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: true
    state: absent
  tags:
    - packages
