---
- name: install rpmfusion repositories
  dnf:
    name: [ "{{ repo_rpmfusion | join(',') }}" ]
    state: present
  tags:
    - packages
    - common

- name: install spotify repository
  get_url:
    url: "{{ repo_spotify_url }}"
    dest: "/etc/yum.repos.d/fedora-spotify.repo"
    owner: root
    group: root
    mode: 0644
  tags:
    - packages
    - common

- name: install iridium repository
  get_url:
    url: "{{ repo_iridium_url }}"
    dest: "/etc/yum.repos.d/iridium-browser.repo"
    owner: root
    group: root
    mode: 0644
  tags:
    - packages
    - common

- name: install dropbox repository
  copy:
    src: "etc/yum.repos.d/dropbox.repo"
    dest: "/etc/yum.repos.d/dropbox.repo"
    owner: root
    group: root
    mode: 0644
  tags:
    - packages
    - common

- name: install fedora third party repository
  dnf:
    name: fedora-workstation-repositories
    state: present
  tags:
    - packages
    - common

- name: install packages
  dnf:
    name: "{{ packages }}"
    state: present
    enablerepo:
      - fedora-cisco-openh264
      - google-chrome
  tags:
    - packages
    - common

- name: install keybase
  dnf:
    name: "{{ package_keybase_url }}"
    state: present
  tags:
    - packages
    - keybase

- name: install zoom
  dnf:
    name: "{{ package_zoom_url }}"
    state: present
  tags:
    - packages
    - zoom

- name: autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: true
    state: absent
  tags:
    - packages
    - common
