---
- name: add/enable rpmfusion repositories [free, nonfree]
  dnf:
    disable_gpg_check: true
    name: [ "{{ repo_rpmfusion | join(',') }}" ]
    state: present
  tags:
    - packages

- name: add/enable iridium repository
  command: dnf config-manager --add-repo "{{ repo_iridium }}"
  tags:
    - packages

- name: add/enable dropbox repository
  copy:
    src: "etc/yum.repos.d/dropbox.repo"
    dest: "/etc/yum.repos.d/dropbox.repo"
    owner: root
    group: root
    mode: 0644
  tags:
    - packages

- name: install packages
  dnf:
    name: "{{ packages }}"
    state: present
  tags:
    - packages

- name: install third party packages [keybase, zoom]
  dnf:
    disable_gpg_check: true
    name: [ "{{ package_third_party | join(',') }}" ]
    state: present
  tags:
    - keybase
    - packages
    - zoom

- name: autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: true
    state: absent
  tags:
    - packages
