---
- name: Ensure install packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_common }}"

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
