---
- name: Create directory nashroot and nashpath
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ nash_path }}"
    - "{{ nash_root }}"
  become: no

- name: Clone nash repository
  git:
    repo: "{{ nash_repo }}"
    dest: "{{ golang_path }}/src/github.com/NeowayLabs/nash"
    version: "{{ nash_version }}"
  become: no

- name: Ensure install nash
  shell: |
    PATH=$PATH:$GOROOT/bin
    export PATH
    make -e install
  args:
    chdir: "{{ golang_path }}/src/github.com/NeowayLabs/nash"
  environment:
    NASHPATH: "{{ nash_path }}"
    NASHROOT: "{{ nash_root }}"
    GOPATH: "{{ golang_path }}"
    GOROOT: "{{ golang_root }}"
  become: no

- name: Copy nash init
  template:
    src: "config/nash/init.j2"
    dest: "{{ nash_path }}/init"
  become: no

- name: Copy nash profile to all users
  template:
    src: etc/profile.d/nash.sh.j2
    dest: /etc/profile.d/nash.sh

- name: Copy nash alias, colors, prompt, etc.
  copy:
    src: "config/nash/{{ item }}"
    dest: "{{ nash_path }}/{{ item }}"
  with_items:
    - aliases.sh
    - colors.sh
    - prompt.sh
  become: no

- name: Create directory ~/bin
  file:
    path: "{{ home_path }}/bin"
    state: directory
    mode: 0755
  become: no

- name: Copy small utils
  copy:
    src: "bin/{{ item }}"
    dest: "{{ home_path }}/bin/{{ item }}"
    mode: 0755
  with_items:
    - exec
    - pbcopy
    - pbpaste
  become: no
