---
- name: Ensure install tmux
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - tmux
    - tmux-powerline

- name: Install tmux config
  copy:
    src: "tmux.conf"
    dest: "{{ home_path }}/.tmux.conf"
  become: no
