# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# PLAN9
PLAN9ROOT=/usr/local/plan9
export PATH="$PATH:$PLAN9ROOT/bin"

# GO
export GOROOT=/usr/local/go
export GOPATH="$HOME/projects/go1.9.2-workspace/"
export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"

# NASH
NASHROOT="$HOME/nashroot/"
export PATH="$PATH:$NASHROOT/bin"

# vpn
alias vpn="sudo openvpn --cd $HOME/.config/openvpn --config rohan.ovpn"

# myip
alias myip='dig +short www.google.com @8.8.8.8'

# encfs
alias encfs_mount="ENCFS6_CONFIG=$HOME/.encfs6.xml encfs $HOME/Dropbox/Work $HOME/Private"

# nvim
alias vim="nvim"

# nvim /etc/hosts
alias h="sudo nvim /etc/hosts"
