---
- name: Ensure install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present

- name: Check if docker repository exists
  stat:
    path: /etc/yum.repos.d/docker
  register: docker_repo

- name: Ensure install docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  when: not docker_repo.stat.exists

- name: Make sure docker from distro is not installed
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: Ensure install docker/docker-compose
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-compose
