---
- hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - vars/main.yaml

  roles:
    - { role: ansible-role-fedora-base }
    - { role: ansible-role-dotfiles }
    - { role: docker, tags: docker }
    - { role: golang, tags: golang }
