---
- name: Ensure install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present

- name: Ensure install docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Make sure docker from distro is not installed
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: Ensure install docker
  dnf:
    name: docker-ce
    state: present

- name: Ensure your user in the docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
